<<<<<<< HEAD
# Generated by Django 4.0 on 2023-11-14 01:56
=======
# Generated by Django 4.0 on 2023-11-23 14:03
>>>>>>> develop

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
<<<<<<< HEAD
        ('users', '0001_initial'),
        ('gathering', '0001_initial'),
=======
        ("gathering", "0001_initial"),
        ("users", "0001_initial"),
>>>>>>> develop
    ]

    operations = [
        migrations.AddField(
            model_name="gatheringpost",
            name="author_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.user"
            ),
        ),
        migrations.AddField(
<<<<<<< HEAD
            model_name='comment',
            name='author_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
=======
            model_name="comment",
            name="author_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.user"
            ),
>>>>>>> develop
        ),
        migrations.AddField(
            model_name="comment",
            name="post_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="gathering.gatheringpost",
                verbose_name="gatherings",
            ),
        ),
    ]