# Generated by Django 4.0 on 2023-11-23 15:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gathering', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatheringpost',
            name='deadline',
            field=models.DateTimeField(null=True, verbose_name='deadline'),
        ),
        migrations.AddField(
            model_name='gatheringpost',
            name='summary',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='summary'),
            preserve_default=False,
        ),
    ]
