# Generated by Django 4.0 on 2023-11-25 17:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gathering', '0003_gatheringlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatheringpost',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='deadline'),
            preserve_default=False,
        ),
    ]
