# Generated by Django 4.0 on 2023-11-26 09:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gathering', '0004_alter_gatheringpost_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatheringpost',
            name='contact',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gatheringpost',
            name='division',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
