# Generated by Django 4.0 on 2023-11-29 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gathering', '0005_gatheringpost_contact_gatheringpost_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatheringpost',
            name='period',
            field=models.IntegerField(),
        ),
    ]
