# Generated by Django 4.2.4 on 2023-09-29 09:27

from django.db import migrations, models
import modira.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.BigAutoField(max_length=20, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, validators=[modira.validators.validate_email])),
                ('nickname', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20, validators=[modira.validators.validate_password])),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
