# Generated by Django 4.0 on 2023-11-23 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("qna", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="qnapost",
            name="author_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.user"
            ),
        ),
        migrations.AddField(
            model_name="like",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="qna.qnapost"
            ),
        ),
        migrations.AddField(
            model_name="like",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.user"
            ),
        ),
        migrations.AddField(
            model_name="interestedpost",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interested_users",
                to="qna.qnapost",
            ),
        ),
        migrations.AddField(
            model_name="interestedpost",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interested_posts",
                to="users.user",
            ),
        ),
        migrations.AddField(
            model_name="answercomment",
            name="answer_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="qna.answer",
                verbose_name="answers",
            ),
        ),
        migrations.AddField(
            model_name="answercomment",
            name="author_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.user"
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="author_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.user"
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="qna_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="qna.qnapost",
                verbose_name="qnas",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="like",
            unique_together={("user", "post")},
        ),
    ]
