# Generated by Django 4.0 on 2023-11-03 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('qna', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qnapost',
            name='author_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AddField(
            model_name='answer',
            name='author_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AddField(
            model_name='answer',
            name='qna_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qna.qnapost', verbose_name='qnas'),
        ),
    ]