# Generated by Django 4.0 on 2023-11-26 10:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qnapost',
            name='summary',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
