# Generated by Django 2.2 on 2023-07-31 05:22

from django.db import migrations

def save_email_domain(apps, schema_editor):
    User = apps.get_model('coplate', 'User')
    for user in User.objects.all():
        user.email_domain = user.email.split('@')[1]
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('coplate', '0006_user_email_domain'),
    ]

    operations = [
    ]
