# Generated by Django 4.2.4 on 2023-09-29 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modira', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
