# Generated by Django 2.2 on 2023-07-31 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coplate', '0005_auto_20230726_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='intro',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
